services:
  frontend:
    build: .
    container_name: client-manager-frontend
    environment:
      - VITE_API_URL=http://api:3000
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build: ./backend
    container_name: client-manager-api
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=client_manager
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: client-manager-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=client_manager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: